version: '3.8'

services:
  vulnerable-web:
    build: ./vulnerable-web
    ports:
      - "8080:5000"
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  fileserver:
    build: ./fileserver
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - files:/srv/samba/

  scanner:
    build: ./scanner
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scanner:/scanner

volumes:
  files:
